import {
  TIPOS_CONVENCIONALES,
  formatearReporte,
  parsearGitLog,
  validarAsunto,
  validarCommits,
  validarMensaje,
  type MensajeCommit,
} from "./conventional-commits";

const commit = (asunto: string, cuerpo = ""): MensajeCommit => ({
  sha: "a".repeat(40),
  asunto,
  cuerpo,
});

describe("validarAsunto", () => {
  it.each([
    "feat(venta): confirmar venta emite FACTURA con NCF",
    "fix: corregir redondeo de ITBIS en líneas mixtas",
    "fix(ncf-secuencia): bloquear rango agotado",
    "refactor(compra/core): extraer cálculo de costo promedio",
    "chore(deps): subir prisma a 7.10.0",
    "feat(api)!: romper el contrato de POST /ventas",
    "revert: feat(venta): confirmar venta emite FACTURA",
    "migrate(db): aplicar defaults de crédito en CLIENTE",
    "feat(venta,inventario): conectar salidas de venta y cancelación",
    'Revert "feat(venta): confirmar venta emite FACTURA"',
  ])("acepta %s", (asunto) => {
    expect(validarAsunto(asunto)).toEqual([]);
  });

  it.each([
    [""],
    ["Confirmar venta emite NCF"],
    ["feat venta: sin dos puntos"],
    ["feat(venta):"],
    ["feat(venta): "],
    ["FEAT(venta): tipo en mayúsculas"],
    ["feature(venta): tipo inexistente"],
    ["feat(Venta): ámbito en mayúsculas"],
    ["feat(venta ncf): ámbito con espacio"],
    ["wip: no es un tipo del changelog"],
  ])("rechaza %s", (asunto) => {
    expect(validarAsunto(asunto).length).toBeGreaterThan(0);
  });

  it("cubre todos los tipos declarados", () => {
    for (const tipo of TIPOS_CONVENCIONALES) {
      expect(validarAsunto(tipo + ": descripción")).toEqual([]);
    }
  });
});

describe("validarMensaje", () => {
  it("acepta cuerpos humanos, con Co-Authored-By de personas", () => {
    const mensaje = commit(
      "feat(venta): confirmar venta",
      "Explica el porqué.\n\nCo-Authored-By: Maria Perez <maria@example.com>",
    );
    expect(validarMensaje(mensaje)).toEqual([]);
  });

  it.each([
    "Co-Authored-By: Claude <noreply@anthropic.com>",
    "co-authored-by: cursor-agent <bot@cursor.sh>",
    "🤖 Generated with [Claude Code](https://claude.com/claude-code)",
    "Generated by ChatGPT",
  ])("rechaza la atribución de IA: %s", (cuerpo) => {
    expect(validarMensaje(commit("feat(venta): x", cuerpo)).length).toBeGreaterThan(0);
  });

  it("hereda los motivos del asunto", () => {
    expect(validarMensaje(commit("asunto inválido", "")).length).toBeGreaterThan(0);
  });
});

describe("validarCommits", () => {
  it("devuelve solo los inválidos, con sus motivos", () => {
    const invalidos = validarCommits([
      commit("feat(venta): ok"),
      commit("arreglo rápido"),
      commit("fix(ncf): ok"),
      commit("chore: ok", "Co-Authored-By: Claude <noreply@anthropic.com>"),
    ]);
    expect(invalidos.map((c) => c.asunto)).toEqual([
      "arreglo rápido",
      "chore: ok",
    ]);
    expect(invalidos[0]?.motivos).toHaveLength(1);
    expect(invalidos[1]?.motivos).toHaveLength(1);
  });
});

describe("parsearGitLog", () => {
  const SEPARADOR_CAMPO = "\u001f";
  const SEPARADOR_REGISTRO = "\u001e";

  it("parsea varios commits, incluidos los cuerpos multilínea", () => {
    const salida = [
      "sha1" + SEPARADOR_CAMPO + "feat(venta): uno" + SEPARADOR_CAMPO + "cuerpo\n\nmás cuerpo\n" + SEPARADOR_REGISTRO,
      "sha2" + SEPARADOR_CAMPO + "fix(ncf): dos" + SEPARADOR_CAMPO + "\n" + SEPARADOR_REGISTRO,
      "",
    ].join("\n");

    const commits = parsearGitLog(salida);

    expect(commits).toHaveLength(2);
    expect(commits[0]).toEqual({
      sha: "sha1",
      asunto: "feat(venta): uno",
      cuerpo: "cuerpo\n\nmás cuerpo",
    });
    expect(commits[1]?.asunto).toBe("fix(ncf): dos");
    expect(commits[1]?.cuerpo).toBe("");
  });

  it("devuelve lista vacía para un rango sin commits", () => {
    expect(parsearGitLog("")).toEqual([]);
  });
});

describe("formatearReporte", () => {
  it("incluye el resumen, los motivos y el formato esperado", () => {
    const reporte = formatearReporte(
      [{ sha: "abcdef1234567890", asunto: "mal asunto", motivos: ["no sigue el formato"] }],
      3,
    );
    expect(reporte).toContain("1 de 3 commit(s)");
    expect(reporte).toContain("abcdef1");
    expect(reporte).toContain("no sigue el formato");
    expect(reporte).toContain("Formato esperado");
  });
});
