-- ============================================================
-- Migration: usuario_auth_user_id
-- Audit remediation finding v2r-01 (ADR-014 binding hardening)
--
-- Binds each USUARIO row to the immutable Supabase Auth identifier (`sub`,
-- a UUID) instead of trusting the mutable synthetic email.
--
-- WHY (the vulnerability being closed):
--   ADR-014 makes the access identifier `nombreUsuario` and the email a
--   NON-credential: Supabase Auth only receives an internal synthetic email
--   `<nombreUsuario>@users.systemfact.internal`. The previous identity
--   resolution decoded `nombreUsuario` back OUT of the JWT email and looked
--   USUARIO up by it. That is not tamper-resistant, because an Auth admin can
--   change a user's email; whoever controls that attribute would control which
--   USUARIO row (and therefore which empresa) the request resolves to. The
--   Auth `sub` is immutable and was never read, never stored.
--
-- WHAT:
--   1. A nullable `authUserId UUID` column on USUARIO.
--   2. A UNIQUE PARTIAL index over it, WHERE "authUserId" IS NOT NULL.
--
-- The index is written by hand rather than generated by Prisma because the
-- Prisma DSL cannot express a partial unique index. The predicate is kept
-- explicit and reviewable here, and the column is deliberately NOT annotated
-- `@unique` in schema.prisma (Prisma only surfaces `@unique`/`@id` fields via
-- `findUnique`, and would misdescribe a partial index as a total one).
--
-- NULLABLE ON PURPOSE, NO BACKFILL:
--   The `sub` values live in Supabase Auth, not in Postgres, so no honest
--   offline backfill exists. Fabricating UUIDs would be worse than NULL. Every
--   pre-existing row therefore keeps `authUserId IS NULL` until its owner logs
--   in again; the login flow binds the real `sub` at that moment.
--
-- ONE-TIME CONSEQUENCE OF DEPLOYING THIS (accepted):
--   Users holding a session issued BEFORE this migration resolve no identity
--   from `sub`, because their row still has `authUserId IS NULL`. Every such
--   user is asked to log in exactly once more; the login writes the binding and
--   from then on resolution is by `sub`. This is NOT worked around with a
--   silent email fallback on the per-request path - that fallback is precisely
--   the vulnerability this migration removes.
--
-- Post-partial index semantics: rows with NULL are excluded from the index
-- entirely, so any number of unlinked users coexist and remain index-free,
-- while each non-NULL `sub` maps to at most one USUARIO row database-wide.
--
-- ROLLBACK:
--   DROP INDEX "usuario_auth_user_id_uk";
--   ALTER TABLE "USUARIO" DROP COLUMN "authUserId";
-- ============================================================

-- AlterTable
ALTER TABLE "USUARIO" ADD COLUMN     "authUserId" UUID;

-- CreateIndex (partial unique; predicate is explicit, not Prisma-generated)
CREATE UNIQUE INDEX "usuario_auth_user_id_uk"
ON "USUARIO" ("authUserId")
WHERE "authUserId" IS NOT NULL;